name: Upload to DigitalOcean - Hi3JP
on:
  push:
    branches: [ "main" ]
    paths:
        - 'pustaka/Hi3JP/**'
  workflow_dispatch:

env:
  DESTINATION-PATH: 'cl-meta/pustaka/Hi3CN'
  CDN-URL: 'https://cdn.collapselauncher.com'

jobs:
  pustaka-Hi3JP:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone --depth 1 https://github.com/CollapseLauncher/CollapseLauncher-MetaRepo.git cl-meta

      - name: Upload
        uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.DO_SPACES_KEY}}
          secret_key: ${{ secrets.DO_SPACES_SECRET }}
          space_name: ${{ secrets.DO_SPACES_NAME }}
          space_region: ${{ secrets.DO_SPACES_REGION }}
          source: '${{ env.DESTINATION-PATH }}'
          out_dir: '${{ env.DESTINATION-PATH }}'
          cdn_domain: ${{ env.CDN-URL }}
          versioning: false
          
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_PURGE_TOKEN }}

      - name: Purge DigitalOcean cache
        run: |
          doctl compute cdn flush a94b5dfc-8dfe-4060-99ec-14526d813c22 --trace --files '"${{ env.DESTINATION-PATH }}/*"'

      - name: Purge Cloudflare cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_PURGE_CACHE_ZONEID_CL }}/purge_cache" \
              -H "Authorization: Bearer ${{ secrets.CF_PURGE_CACHE_TOKEN_CL }}" \
              -H "Content-Type: application/json" \
              --data "{ \"purge_everything\": true }"