name: Upload to R2
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  pustaka-Hi3SEA:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone --depth 1 https://github.com/CollapseLauncher/CollapseLauncher-MetaRepo.git cl-meta

      - name: Sync Metadata objects
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: cl-meta/pustaka/Hi3SEA
          destination-dir: cl-meta/pustaka/Hi3SEA
          output-file-url: false

  pustaka-Hi3Global:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone --depth 1 https://github.com/CollapseLauncher/CollapseLauncher-MetaRepo.git cl-meta

      - name: Sync Metadata objects
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: cl-meta/pustaka/Hi3Global
          destination-dir: cl-meta/pustaka/Hi3Global
          output-file-url: false

  pustaka-Hi3JP:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone --depth 1 https://github.com/CollapseLauncher/CollapseLauncher-MetaRepo.git cl-meta

      - name: Sync Metadata objects
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: cl-meta/pustaka/Hi3JP
          destination-dir: cl-meta/pustaka/Hi3JP
          output-file-url: false

  pustaka-Hi3KR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone --depth 1 https://github.com/CollapseLauncher/CollapseLauncher-MetaRepo.git cl-meta

      - name: Sync Metadata objects
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: cl-meta/pustaka/Hi3KR
          destination-dir: cl-meta/pustaka/Hi3KR
          output-file-url: false

  pustaka-Hi3TW:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone --depth 1 https://github.com/CollapseLauncher/CollapseLauncher-MetaRepo.git cl-meta

      - name: Sync Metadata objects
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: cl-meta/pustaka/Hi3TW
          destination-dir: cl-meta/pustaka/Hi3TW
          output-file-url: false

  pustaka-Hi3CN:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone --depth 1 https://github.com/CollapseLauncher/CollapseLauncher-MetaRepo.git cl-meta

      - name: Sync Metadata objects
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: cl-meta/pustaka/Hi3CN
          destination-dir: cl-meta/pustaka/Hi3CN
          output-file-url: false

  Clear-CF-Cache:
    runs-on: ubuntu-latest
    if: always()
    needs: [pustaka-Hi3CN, pustaka-Hi3SEA, pustaka-Hi3Global, pustaka-Hi3JP, pustaka-Hi3TW, pustaka-Hi3KR]
    steps:
      - name: Purge Cloudflare cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_PURGE_CACHE_ZONEID }}/purge_cache" \
              -H "Authorization: Bearer ${{ secrets.CF_PURGE_CACHE_TOKEN }}" \
              -H "Content-Type: application/json" \
              --data "{ \"purge_everything\": true }"